### ISSUE TITLE
What are the requirements for the returns file?

### ISSUE THREAD

**Issue by YanaHeyv** [LemaireJean-Baptiste/eventstudy#11]
Hey, first of all thank you for creating this amazing package, I like it a lot! 
I am just struggling with the returnsfile. What are the requirements?

I created my csv file containing stockprices with yahoofinancials, creating an output like this:
![image](https://user-images.githubusercontent.com/94294184/141764993-1b95623d-445e-4aab-97bd-29d64a4ad23b.png)
But when I run the event study, I do not get the right output, I get an error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yanah/Documents/BEDRIJFSECONOMIE/Thesis/Results/Event1.py", line 5, in <module>
    es.Single.import_returns('prices.csv', is_price=True, log_return=False, date_format= '%Y-%m-%d')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eventstudy/single.py", line 327, in import_returns
    data = read_csv(path, format_date=True, date_format=date_format)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eventstudy/utils.py", line 112, in read_csv
    df[date_column] = pd.to_datetime(df[date_column], format=date_format)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'date'

What am I doing wrong with my file?

Kind regards

**Comment by LemaireJean-Baptiste** [comment]
Hello YanaHeyv, thanks for your message.
The file need to follow the specifications of the package. The first column must have for name "date".
So you have to modify the first line as follow : "date,TSLA,MSFT,FB,SPY"

It should solve your issue.

_You can see in the error log : "KeyError: 'date'", it means that in your database, the package didn't find the date column._

**Comment by YanaHeyv** [comment]
Dear
Thank you. When I adjusted it and added date, I got this error:
/usr/local/bin/python3 /Users/yanah/Documents/BEDRIJFSECONOMIE/Thesis/Results/Event1.py
Traceback (most recent call last):
  File "/Users/yanah/Documents/BEDRIJFSECONOMIE/Thesis/Results/Event1.py", line 8, in <module>
    event = es.Single.FamaFrench_3factor(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eventstudy/single.py", line 593, in FamaFrench_3factor
    (security_returns,) = cls._get_parameters(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eventstudy/single.py", line 292, in _get_parameters
    raise DataMissingError(param_name, column, len(result), start + end)
eventstudy.exception.DataMissingError: Some data are missing for (TSLA) in 'returns''.
Tips: Check if parameters are up-to-date and contain all needed value.

Process finished with exit code 1

![image](https://user-images.githubusercontent.com/94294184/141810045-71f49346-cbdc-4e6a-9283-db536e98cc34.png)
